### PR TITLE
fix: babel config lookup

### LINKED ISSUE #200: .babelrc.js ignored
The `.babelrc` filename is hardcoded in https://github.com/netlify/netlify-lambda/blob/d9f70def3f569616c4a0fb659f627e0b0cfd6000/lib/build.js#L18-L30, meaning that alternatives such as `.babelrc.js` are ignored.
Ideally Babel's own config resolution should be used instead of reimplementing it so errors like this cannot happen.

### PR DESCRIPTION
**Pull request by Robin-Hoodie**
New PR from different branch which closes #359 . 

In comparison to #359 the following has been added:

- Added tests finding babel config file
- Refactored logic to find babel config file to use `find-up`'s matcher function and improve performance

Closes #200, #188

### CODE REVIEW

**Review by erezrokah — COMMENTED** [review]
Hi @Robin-Hoodie and sorry for the late reply.
Thank you again for pushing this fix. I think I wasn't able to explain myself before when I mentioned monorepo support. I've added a few commits to cleanup the tests and a test case describing what I had in mind:
https://github.com/netlify/netlify-lambda/pull/364/files#diff-dd24f19d79300a10592927150e05758644fc84a1ae5c7b7844ae0909416738d2R153
The scenario we'd like to support is if someones has a babel config file in the root of a monorepo, but runs `netlify-lambda` from the a directory of a specific package (hence the `cwd` is the directory of that package).

Please let me know what you think of the changes I made and if my explanation is clear enough.

File: lib/build.js [hunk 1]
```diff
@@ -15,25 +41,52 @@ function getBabelTarget(envConfig) {
...
+      cwd: functionsDir,
+    },
   );
+  return Boolean(babelConfigFile);
 }
 
-function webpackConfig(dir, { userWebpackConfig, useBabelrc } = {}) {
+function webpackConfig(
+  dir,
+  { userWebpackConfig, useBabelrc, cwd = process.cwd() } = {},
```
Comment (erezrokah) [inline lib/build.js:82]: `cwd` argument is only here so we can test the monorepo setup

**Comment by erezrokah** [comment]
Ok, so after reading https://babeljs.io/docs/en/config-files#file-relative-configuration and https://babeljs.io/docs/en/config-files#monorepos it might be better to use `babel` APIs for this to make sure we don't miss any edge case. WDYT?

File: lib/build.js [hunk 2]
```diff
@@ -41,7 +41,20 @@ function getBabelTarget(envConfig) {
   return unknown ? '8.15.0' : current.replace(/^nodejs/, '');
 }
 
+function getRepositoryRoot(functionsDir) {
+  const gitDirectory = findUp.sync('.git', {
+    cwd: functionsDir,
+    type: 'directory',
+  });
+  if (gitDirectory === undefined) {
+    return functionsDir;
```
Comment (Robin-Hoodie) [inline lib/build.js:50]: Would it not make more sense to fall back to `process.cwd` here?  
Having a babel config file in the root directory and a functions folder in a subdirectory would otherwise fail to find the babel config file in a non-git project

**Comment by Robin-Hoodie** [comment]
> Ok, so after reading https://babeljs.io/docs/en/config-files#file-relative-configuration and https://babeljs.io/docs/en/config-files#monorepos it might be better to use `babel` APIs for this to make sure we don't miss any edge case. WDYT?

That would definitely be the easiest and it's what I tried to do first. However, I don't know if `@babel/core` exposes that logic anywhere. None of the [options for the Babel core API](https://babeljs.io/docs/en/babel-core) seem to be about checking for the existance of a babel config file.

The logic for looking [up a babel config file](https://github.com/babel/babel/blob/master/packages/babel-core/src/config/files/configuration.js) does not seem to be exposed as far as I can tell

File: lib/build.spec.js [hunk 3]
```diff
@@ -145,6 +149,30 @@ describe('build', () => {
...
+              `${directory}/packages/netlify-site/functions/index.js`,
+              'module.exports = () => console.log("hello world")',
+            ),
+            writeFile(`${directory}/babel.config.js`, ''),
+          ]);
+
+          const stats = await build.run(`packages/netlify-site/functions`, {
+            cwd: directory,
+          });
+          return stats;
```
Comment (Robin-Hoodie) [inline lib/build.spec.js:167]: Nitpicking here, but I would straight up `return await build.run..`, the intermediate `stats` variable seems unnecarry and makes things more confusing (as it's shadowing the outer  `stats` variable)

**Comment by Robin-Hoodie** [comment]
I went over the commits you've added just now. Added 2 comments but great additions overall!

File: lib/build.js (hunk 2 above)
Comment (erezrokah) [reply lib/build.js:50]: Yes it would, good catch!

File: lib/build.spec.js (hunk 3 above)
Comment (erezrokah) [reply lib/build.spec.js:167]: Good point, I'll fix it
